HearthSim/Hearthstone-Deck-Tracker

- Hearthstone Deck Tracker/DeckImporter.cs
Multiple `<div class="deck-list">` can be on the same page. However, it seems that
the div element containing the deck list is also `class="guide-deck-list"`. This
class seems to be unique within the document.
Fix switches deck-list to guide-deck-list.
> Changed import config (hearthstoneplayers)

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
With every new release, I was constantly updating the Config.Instance.DataDir variable to point to my cloud storage, such that I had access to all current decks from different devices. 
I finally decided to to add the ability into the options menu, such that the folder can be set and saved in the config file. It can be found in options > Other > Tracker at the very bottom
> Added the ability to save to an own data directoy

- Hearthstone Deck Tracker/Hearthstone/Game.cs
A single commit to address #601. Commit message copied below.
Originally, card drawn / play / get methods only updated
card.InHandCount for PlayerDeck, not PlayerDrawn. This commit updates
PlayerDrawn as well to make the "Use No Deck" overlay behavior more
consistent with the overlay behavior for when a pre-configured deck is
displayed. Specifically, cards in hand are now highlighted the same way
whether a pre-configured deck is used or not.
> Update Card.InHandCount for PlayerDrawn deck.

- Updater/Updater.csproj
- Updater/app.manifest
This will allow the Updater to work if the executable resides in %ProgramFiles%.
This should do what I was talking about in issue #668. This embeds a manifest file into Updater.exe which tells Windows that it needs to run with administrator privileges. When HDT starts Updater.exe, the user should see a UAC dialog prompting them to elevate the process. When elevated, Updater.exe can write to %ProgramFiles%, otherwise it will fail.
http://www.codeproject.com/Articles/17968/Making-Your-Application-UAC-Aware
Tested this by forcing HDT to update (this code is not present here, as it was just for the test). It seemed to do the job. I'm not too familiar with this stuff though so if anyone else has any expertise with this, please take a look and make sure I didn't do anything stupid :)
> Run Updater.exe as administrator (#668)

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Export.cs
- Hearthstone Deck Tracker/Utility/Helper.cs
- Hearthstone Deck Tracker/Windows/MessageDialogs.cs
This changes `EXPORT > SCREENSHOT` and `EXPORT > SAVE AS XML` to present the user with a save file dialog, so they can choose where to save the files. This seems more natural and also allows the feature to work when the executable resides in %ProgramFiles% (issue #668).
> Save file dialog on EXPORT > SCREENSHOT and SAVE AS XML

- Updater/Program.cs
This allows the updater to update itself. 
Previously wasn't copying the Updater_new.exe to the correct path.
> Fix updater updating itself

- Updater/Program.cs
This should at least stop the updater from crashing if it fails to delete the temp folder on cleanup (probably due to file handles still being open after enumerating through the files - issue #526).
It won't matter anyway if the temp folder doesn't get cleaned up, so we can get away with just fixing the symptom. Either way, the folder should get deleted next time the Updater starts (by then the file handles should have been released).
> Don't crash if Updater fails to cleanup

- Hearthstone Deck Tracker/DeckImporter.cs
- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/packages.config
Updated deck importer to work with the new TempoStorm design. The deck data is requested with a Json Post request and the resulting Json response is parsed to extract the card information, using Newtonsoft.Json package.
> Update TempoStorm deck importer

- Hearthstone Deck Tracker/Controls/NewDeckPickerItem.xaml
- Hearthstone Deck Tracker/Hearthstone/Deck.cs
I wanted to see actual win-loss counts for my decks, particularly for arena.
Textblock for WinPercentString was copied into a Viewbox to allow
scaling, so large numbers don't get clipped. Both Textblocks were moved
to a grid for positioning.
> Added Win-Loss count to NewDeckPicker

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Game.cs
- Hearthstone Deck Tracker/HsLogReader.cs
- Hearthstone Deck Tracker/IGameHandler.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
- Hearthstone Deck Tracker/Windows/OpponentWindow.xaml
- Hearthstone Deck Tracker/Windows/OpponentWindow.xaml.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
- Hearthstone Deck Tracker/Windows/PlayerWindow.xaml
- Hearthstone Deck Tracker/Windows/PlayerWindow.xaml.cs
http://i.imgur.com/bFPI4wA.png
Hi there!
I tried to add this functionality since some times it is hard to keep track of the fatigue damage since the history on the left is so short.
The fatigue counter is located under the the card counter of each deck but only is displayed once the deck has 0 cards.
But I ran into a little problem. I'm not sure why, but I'm unable to set this counter as separate option (it just won't show up) so I ended up hooking it up to the card counter, meaning that whenever the card counter is enabled so is the fatigue counter. It makes sense, altough it is not correct in terms of implementation. I'm hoping once it gets merged someone can quickfix it or if someone could share some light in what I might be missing, I'd be grateful. 
Hope this is useful!
> Added Fatigue counter that shows up once there are no cards in a deck.

- Hearthstone Deck Tracker/HearthStats/API/HearthStatsAPI.cs
- Hearthstone Deck Tracker/HearthStats/API/Objects/DeckObject.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Import.cs
Since the introduction of the 'open website' button, I assume we don't want to put the URL in the note anymore when importing from the web or NetDeck, or when we download decks from HearthStats.
I wanted to build on this commit in the archived decks branch, but it doesn't seem logically related to that feature so I created a separate pull request for it. This way the work is not going to be sitting in that branch for however long it's going to take to finish that feature off and be merged into master.
I also changed the tag we put into the HearthStats note to `[HDT-source=<url>]` rather than `[source=<url>]`. This is mainly because I want to use `[HDT-archived]` instead of `[archived]`, because it's more likely to not be used by the user (small chance but possible). So I thought to be …
> Don't put URL in note on import or sync

- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
Notes and stats context wasn't set to the active deck at startup. This could lead to a null ref exception if you try to edit a note immediately after starting up.
> Fix notes and stats context at startup

- Hearthstone Deck Tracker/HearthStats/API/HearthStatsAPI.cs
- Hearthstone Deck Tracker/HearthStats/API/HearthStatsManager.cs
Thought I'd cherry pick this out of the archived branch so it can be used when fixing #745.
Note that it doesn't fix #745 by itself. It just takes the note from the latest version (the master deck) rather than v1.0 of a deck.
> Use correct version's note when syncing

- Hearthstone Deck Tracker/HearthStats/API/HearthStatsAPI.cs
- Hearthstone Deck Tracker/HearthStats/API/HearthStatsManager.cs
Fix syncing deck name and tags of v1.0 rather than of latest version of the deck, since this might be old metadata that has since been changed.
This was the same problem as the old note being synced, so should have noticed it at the time. The old bug could be reproduced by: Logout of HearthStats. Create a new deck. Edit deck to v1.1. Change the name of deck (resave as 1.1 again). Change tags. Login to Hearthstats and sync. It will upload the old deck name and no tags (or whatever the old tags were).
> Fix syncing old deck metadata

- Hearthstone Deck Tracker/FlyoutControls/DeckNotes.xaml.cs
Editing deck note now triggers sync properly when the selected deck changes while the notes flyout is still open.
> Fix deck note syncing when selected deck changes

- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
This is a better fix for what I did in [pull/746](https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/746).
I've extracted out the `OnSelectedDeckChanged` implementation to another method and now call that method on start. This allows us to remove the `SetupNotesAndStats` method, and remove the extra stuff at the end of `LoadConfig` that never really felt like it belonged there.
I think everything gets set up correctly on start now just as it would when you choose a deck from the deck picker. I had to reorder some things in the extracted method to make sure the cards were sorted in the right order in the overlay on start, so hopefully this doesn't introduce any more bugs like that that I'm not seeing, but I think it's fine.
> Extract method refactor for OnSelectedDeckChanged

- Hearthstone Deck Tracker/Controls/DeckPicker.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Edit.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_NewDeck.cs
This moves the `MainWindow.DeselectDeck` code into the `SelectDeck(null)` code path. Think this reduces some code duplication.
Also fixes a bug where the version combo box was still visible after you click `TRACKER > USE NO DECK`.
> Refactor DeselectDeck into SelectDeck(null) code path

- Hearthstone Deck Tracker/DeckExporter.cs
The CardHasLock method was always returning false due to maxBrightness being incorrectly set to 0.
> Fix card lock detection

- Hearthstone Deck Tracker/DeckExporter.cs
Just added this simple change to remember text in clipboard after the export instead of erasing it all. Tried storing other things like images but would get some errors and it's not worth trying to get anything else working since 99% of the clipboard is text anyway.
> Exporter now remembers text in clipboard and restores it if "Paste names from clipboard" option is used.

- Hearthstone Deck Tracker/MainWindow/MainWindow_NewDeck.cs
I'd like to be able to Set and Save a deck from within a plugin. Currently SaveDeck is private.
Also I'd like to be able to not show the "the deck doesn't contain 30 cards" confirmation as this will break automation.
This is is allow the following feature in a plugin:
https://github.com/rembound/Arena-Helper/issues/11
Let me know your thoughts.
> Allow Plugins to save decks in HDT

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/DeckExporter.cs
With the new collection manager layout, the mana and sets filters are different. The mana filters now toggle on and off and the sets filter has moved. This is also the cause of a problem when exporting decks #1106 #1091.
Changed the `DeckExporter.ClickAllCrystal` to work with the new layout and added support to always change the set to *All Sets*.
I added some new values to `Config.cs`, I'm not sure how this works with the user's current config file - does something need to be added to change their local values?
> Fix export to hearthstone collection filters after latest patch

- Hearthstone Deck Tracker/LoginWindow.xaml.cs
Added a check to make sure _controller was opened before we attempt to close since there are some validations that are not handled by a third party.
> Fixed login issue "Crash on incorrect password" (#1120)

- Hearthstone Deck Tracker/Hearthstone/Game.cs
If the id parameter is e.g. "HERO_07", the regex matched HERO_0. This causes the function to detect an unknown hero and return null. Shouldn't it be * instead + in the end?
> fix hero detection regex

- Hearthstone Deck Tracker/HsLogReader.cs
Fixed wrongly adding an additional opponent PlayToDeck KeyPoint, when a player PlayToDeck event occurs (issue #1170).
> Fixed wrongly adding an additional opponent PlayToDeck KeyPoint

- HDTTests/HDTTests.csproj
- HDTTests/Hearthstone/CardDbTest.cs
- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/DeckExporter.cs
- Hearthstone Deck Tracker/Enums/GameMode.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerStats.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerStats.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/CardIds.cs
- Hearthstone Deck Tracker/Hearthstone/Game.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/Secret.cs
- Hearthstone Deck Tracker/HsLogReader.cs
- Hearthstone Deck Tracker/Windows/AddGameDialog.xaml
1. Fixed loading of brawl cards from xml, changed from `ValidCardSets` to `InValidCardSets` so it only lists the sets to be excluded - should make future updates smoother. Also, added the invalid card ids from brawl, so `GetActualCards` is correct.
-   Added `GameMode.Brawl` and related logic. Used assets unloading to detect brawl games, seems to work well.
- Small workaround to stop "Brawl" decks from trying to change the deck name on exporting to Hearthstone. Had to use deck tags, couldn't detect the brawl deck manager.
> Various Brawl related fixes

- Hearthstone Deck Tracker/App.config
https://msdn.microsoft.com/en-us/library/dd409252(VS.100).aspx
Not having this set was causing plugins to not load with the exception listed in the page linked above.  Likely others have hit this, and it doesn't seem like a terrible idea to set loadFromRemoteSources...
The exact exception fixed is:
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Presumably this is because I am running some version of …
> Fix plugin loading bug

- Hearthstone Deck Tracker/Enums/Region.cs
The constant 5 is used for China region. Without it we may
get an error when serializing DeckStat to disk:
Instance validation error: '5' is not a valid value for
Hearthstone_Deck_Tracker.Enums.Region.
This fixes #1143.
> Add China region constant

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerExporting.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerExporting.xaml.cs
- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/MainWindow/MainWindow_Export.cs
- Hearthstone Deck Tracker/Utility/Imgur.cs
- Hearthstone Deck Tracker/Windows/MessageDialogs.cs
Added an option under `Tracker > Exporting` to allow deck screenshots to be uploaded to imgur.com. Consists of new `Imgur.cs` class for uploading. Addition of config values for API key and enabling the feature. Changes to `MainWindow_Export.cs` and `MessageDialogs.cs` to cater for uploading.
Also, fixed small issue with screenshot file name being incorrect when selected deck is not active. It turns out this will also fix a crash when no deck is active and screenshot is pressed #1152.
@Epix37 I added the API key I used when testing `public string ImgurClientId = "7e1ab33fda207c2"` to `Config.cs`. If you add it to a release you will probably want to register your own anonymous key for HDT at [imgur](https://api.imgur.com/oauth2/addclient) - takes like two minutes.
> Export deck screenshots to imgur.com

- HDTTests/Hearthstone/DeckTest.cs
- Hearthstone Deck Tracker/DeckExporter.cs
Changed the exporting "rectangles" used for detecting the mana crystal, card lock etc. and made them relative to the window height. It should make the detection more accurate at lower resolutions, and be a possible solution to #1162.
Also, for OCD reasons changed the `DeckTest` to cater for the additional parameter in the `Card` constructor :smile:.
> Make export detection regions relative to window height

- HDTTests/Hearthstone/CardDbTest.cs
- Hearthstone Deck Tracker/Hearthstone/Game.cs
Dreadscale's id is *AT_063t*, the *t* stops it from being included in *ActualCards*.
Couldn't think of a better way than adding an id check at the relevant points, its not great but it works!
Fixes #1291
> Fix Dreadscale not being added to ActualCards

- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml
- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
Reverts Epix37/Hearthstone-Deck-Tracker#1326
Causes HDT MainWindow to be always on top (#1335)
> Revert "Better fix for the alt tab issue (issue #1321)"

- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
This will allow (me in particular) people to access the underlying window attributes for resizing and focus, as well as make override (extension) methods without completely copying and personally modifying the code myself.
This makes for easier plugin development on my end while not costing anything to anyone else
> Add extension to the Window class

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/HsLogReader.cs
- Hearthstone Deck Tracker/LogReader/Handlers/RachelleHandler.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Windows\OverlayWindow.xaml.cs
private void UpdateGoldProgress()
{
var region = (int)_game.CurrentRegion - 1;
if (region >= 0)
{
LblGoldProgress.Text = string.Format("Wins: {0}/3 ({1}/100G)", Config.Instance.GoldProgress[region],
Config.Instance.GoldProgressTotal[region]);
}
}
when _game.CurrentRegion is China 
var region = (int)_game.CurrentRegion - 1;
region ==5-1=4
then the index region is out of GoldProgress and GoldProgressTotal,the same as GoldProgressLastReset
> fix bug about gold tracking

- Hearthstone Deck Tracker/FlyoutControls/DeckStatsControl.xaml.cs
So, it was the Hero Verification that was messing this up. A quick fix that just skips it for brawl. (As for the rest of the brawl craziness, no clue :stuck_out_tongue_winking_eye:)
> Fix hero's being incorrectly assigned in Brawl (#1489, #1492)

- Hearthstone Deck Tracker/DeckExporter.cs
When only one standard and one golden card are in the collection and prioritize golden cards was turned off, only the standard card was imported. Now, one standard and one golden card are imported correctly.
> fixed error with exporting

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Controls/CardToolTipControl.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Hearthstone/Database.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_NewDeck.cs
Add an "Alternative Languages" option, which is a list of languages, allowing the player to:
- Search cards using these languages
- View texts of these languages in card tooltip
This is quite useful for players active in HS communities of different languages.
Screenshot:
> Alternative Languages

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/DeckExporter.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerExporting.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerExporting.xaml.cs
An option to disable the mana cost and card set auto filtering, it might help people having trouble exporting decks (#1217, #1177)?
> Add option to disable auto filtering on export

- HDTTests/BoardDamage/BoardCardTest.cs
- HDTTests/BoardDamage/PlayerBoardTest.cs
- HDTTests/BoardDamage/TestHelper.cs
- Hearthstone Deck Tracker/Utility/BoardDamage/BoardCard.cs
- Hearthstone Deck Tracker/Utility/BoardDamage/PlayerBoard.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
A fix for the board attack when cards are in the wrong zones. Sometimes graveyard, hand and deck. Also, removed the exclusion of Icehowl don't think it was correct in the first place.
Fixed the draw chances 200% thing while I was at it.
> Quick fixes

- Hearthstone Deck Tracker/Controls/Card.xaml
- Hearthstone Deck Tracker/Controls/CardToolTipControl.xaml
- Hearthstone Deck Tracker/Controls/DeckListView.xaml
- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
- Hearthstone Deck Tracker/Replay/Controls/BoardEntity.xaml
- Hearthstone Deck Tracker/Replay/Controls/CardEntity.xaml
- Hearthstone Deck Tracker/Utility/Helper.cs
Tested out problem with the Russian language (#1794, #1783, #1756, #1753, #1623), the OS solutions didn't seem to work for me either.
So, added a new **Font** binding prop on `Card` and `Entity` that only uses *Belwe* if the selected lang  is a *Latin* type language, otherwise it should use the default system font.
There's probably a nicer way, but it works :smile:
> Use default font for non-latin languages

- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPicker.xaml.cs
Canceling editing a deck doesn't change selected version of this deck
anymore.
Fixes: #1822
> Fix deck version switch on canceling deck editing

- Hearthstone Deck Tracker/Utility/User32.cs
The code segment that HDT enters when "Use Advanced Search" is selected never actually returned IntPtr.Zero at any point (just ran through the processes and returned the old _hsWindow).
"Use Advanced Search" seems to be related to Issue #1857 in some form as well.
> Issue #1921 - Close with Hearthstone does not work.

- HDTTests/BoardDamage/PlayerBoardTest.cs
- HDTTests/Hearthstone/CardDbTest.cs
- HDTTests/Hearthstone/WebImportTest.cs
- Hearthstone Deck Tracker/Hearthstone/Database.cs
*Baron Geddon* is being imported as the hero, instead of the card (#1883, #1907). Made `Database.GetCardFromName` be collectible by default, with the option of using a named param to make non-collectible if needed (I don't see anywhere that it is though).
*Also, quick fix for Hearthpwn import test - changed the url.*
> Fix importing non-collectible cards

- Hearthstone Deck Tracker/Windows/MessageDialogs.cs
When exporting with missing cards only Naxx and Promotion cards are highlighted. By adding this sets every other set is highlighted as well.
> Added missing card sets

- README.md
The current readme's help screenshot shows an old version of the app that didn't have the fancy UI elements yet. I did a new screenshot from the newest version and added some help popups on it, trying to mimick Hearthstone's look and feel. I tried to keep things simple, and didn't duplicate elements that have a similar icon (i.e. the player's drawing probabilities has the same icon as the opponent's).
> Improve the readme's help screenshot

- HDTTests/HDTTests.csproj
From 
..\..\..\..\Visual Studio 2015\Projects\HearthDb\HearthDb\bin\Release\HearthDb.dll
To
..\lib\HearthDb.dll
> fix the wrong reference location of  HearthDb.dll in HDTTests project

- HDTTests/HDTTests.csproj
- HDTTests/Hearthstone/ParseCardStringTest.cs
- Hearthstone Deck Tracker/Utility/Helper.cs
A very small thing I noticed. 
If you import a deck from the clipboard and a card has a comma in its name and you use a count with it (e.g. 'Ragnaros, Lightlord x1'), it won't be recognized.
Since only legendaries have commas currently, this will probably never actually cause a problem though :smile:.
> Fix potential error importing from clipboard

- Hearthstone Deck Tracker/Controls/Stats/Constructed/ConstructedGames.xaml
When sorting constructed games by duration it was comparing the string duration rather than the numeric duration.
> Fix sorting constructed games by duration

- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsSearch.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsSearch.xaml.cs
When search is clicked, the text box will auto-focus so the user doesn't have to click on it themselves. 
As always, demonstration: https://www.youtube.com/watch?v=2x4lAIbAoQo
> Focus search box when form loads

- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsSearch.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsSearch.xaml.cs
The search tab will automatically update with search results as user types, as long as they have three or more characters in the text box. 
The search button can still be used for reasons of searching with 2 or less characters, however will probably not be used.
> Search tab updates with search results as user types

- Hearthstone Deck Tracker/API/ActionList.cs
Events registered by disabled plugins should be removed from the ActionList. Disabled plugins shouldn't be able to receive events; if the plugin is disabled it shouldn't be doing anything. In addition the ActionList contains a reference back to the method the plugin passed in which, as there is no Remove method, will prevent the Object where the method is defined from being disposed when the addon is disabled creating a likely memory leak.
> Cleanup events from disabled addons.

- Hearthstone Deck Tracker/Importing/Websites/Manacrystals.cs
When Mana Crystals does not show a set of cards in either the class card or the neutral card sections of the website, a null pointer exception was thrown. 
This change should fix that issue.
> Fix Mana Crystals Import Issue

- README.md
This includes links to the new community discord channel, which is separate from the Developer channel.
> Include DIscord community links in the Readme

- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerPlugins.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerPlugins.xaml.cs
This adds functionality to the plugins flyout control to easily install plugins. It checks for the files dropped ending in `.dll` and will overwrite the file if it is already in the folder (as if it's a plugin update).
> Drag and drop for plugins.

- Hearthstone Deck Tracker.sln
- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/PreBuildEvent.bat
- Hearthstone Deck Tracker/Test.bat
- bootstrap.bat
- generate_resources.bat
Several batch files would throw errors in the original solution and cause problems when the HSDT projects were included in a 3rd party solution (usually a plugin). 
Added error checking to scripts to prevent execution of routines that were contingent upon a successful completion of the previous command.  
Added the ability to disable the PreBuildEvent if you so desired. Fixed missing nuget.exe for VS2017 by using msbuild's new integrated functionality. 
Also rocked a nice ^M in there somewhere.
> Fixed Pre-Build Event Issues and Bootstrap / Resource Gen Errors

- .gitignore
- Hearthstone Deck Tracker/Config.cs
Some of the issues mention it and it was annoying to see a deck named 'ARENA 07-06 03:15' when you played it at 15:15 (in the afternoon).
Also amended .gitignore to ignore the .vs folder where changes were showing up in git.
> Fixes the ambiguity of the date in Arena and Brawl decks

- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
When I used the tutorial I had Hearthstone Deck Tracker.exe not found and resgen.exe not found.  This fixes that.  If this pull request is rejected, then could you change the tutorial to add what worked for me.  Go to HearthstoneDeckTRacker and unload project.  Edit HearthStone Deck Tracker .csproj.  Go twoards the bottom where you will find Target GenerateDesignerFiles.  Add SdkToolsPath="$(TargetFrameworkSDKToolsDirectory)"
after the following Generate Resource.  It will look like this.
```
<Target Name="GenerateDesignerFiles">
<GenerateResource SdkToolsPath="$(TargetFrameworkSDKToolsDirectory)" Sources="Properties/Strings.resx" StronglyTypedLanguage="C#" StronglyTypedClassName="Strings" StronglyTypedNamespace="Hearthstone_Deck_Tracker.Properties" …
```
> Current Tutorial leads to build errors.  This line fixes that

- Hearthstone Deck Tracker/Windows/AddGameDialog.xaml
Removes the SelectionChanged event that hides the ranked info.
> Fix AddGameDialog Region selection

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
If stats recording for spectator mode games is disabled and an active deck
is selected after spectating a gane (e.g. by starting an arena game), the
spectated game is assigned to the active deck because the end of a 0 turn
game is detected erroneously. This commit prevents the detection of a 0
turn game while in menu.
Fixes #3343.
> Fix erroneously recording stats for spectator mode

- bootstrap.bat
Provides some output for new contributors who don't have nuget or git installed (or in path). It will attempt to download the latest recommended nuget if the user requests it, but git cannot operate without files it depends on so it must be installed by the user.
Tested the nuget download script and it works even on Windows 7 without updates as Powershell 2.0 is pre-installed.
> Bootstrap: Provide error output for users without nuget or git

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml.cs
- Hearthstone Deck Tracker/TrayIcon.cs
- Hearthstone Deck Tracker/Windows/MainWindow.xaml.cs
I often hit close but what I really wanted was just to close the window, not to terminate the application. Add a setting that when the close button is hit it will instead minimize. 
I added a public variable to the form that the tray icon can set, I thought this might be better then adding an entire new function.
Unsure about how to handle the localization of Options_Tracker_Settings_CheckBox_CloseToTray
> Add setting to allow closing to tray

- Hearthstone Deck Tracker/Controls/ElementSorter.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayOpponent.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayOpponent.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayPlayer.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayPlayer.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
- Plugins/READ THIS.txt
When I changed the language setting, the overlay player and opponent's panel and combo box language did not change automatically.
I used the ComboBoxHelper to change the language of the combo box automatically.
And I add the ReloadUI function to the player and opponent to automatically change the panel's language.
- [v] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [v] I have already signed the CLA
> Refresh Overlay Player & Opponent's panel and combo box

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
Added tracking for the following cards:
- Creepy Curio
- Haunted Curio
- Old Militia Horn
- Militia Horn
- Surly Mob
- Angry Mob
> Added tracking for several Monster Hunt cards

- HDTTests/Hearthstone/CardDbTest.cs
- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Hearthstone/CardIds.cs
Adds feature for #3717 
Added these entourage cards for Kalimos in the most general and reusable way I could think of. Followed the example of some existing hard-coded dictionaries. 
This dictionary can be added to easily in the future, and will union any additional cards in with the list from the db. 
I also added a unit test to prove entourage cards from the db still work too.
> Add tooltips for Kalimos Invocation cards

- HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsManager.cs
- Hearthstone Deck Tracker/IGameHandler.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
Now, if minion dies after explosive runes or snipe, other secrets still display
> Fix incorrect secret handling

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/DeckManager.cs
- Hearthstone Deck Tracker/Hearthstone/DungeonRun.cs
Fix Dungeon Run deck name incorrectly being called "Monster Hunt"
Fixes https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3697
> Fix Dungeon Run deck name

- HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
In https://hearthstone.gamepedia.com/Advanced_rulebook#Combat , blizzard write that
"If you play Explosive Trap then Freezing Trap, your enemy's Novice Engineer attacking into it will trigger the Explosive Trap and be reduced to -1 Health. The Freezing Trap is a hindering Secret and thus aborts having no target it considers valid.[30] "
> Fix a Freezing Trap issue #3830

- Hearthstone Deck Tracker/API/LogEvents.cs
- Hearthstone Deck Tracker/LogReader/LogWatcherManager.cs
Since the Rachelle log is gone, the Achievements log is the only one that contains GOLD_REWARD messages. This is what the Treasury plugin needs to track quests.
> Added Achievements log watcher to API

- Hearthstone Deck Tracker/Hearthstone/DungeonRun.cs
Blizzard updated the starting decks of various shrines, but since it was through an hotfix, the initial decklist on the client is wrong and caused HDT to struggle finding "the correct deck".
> Update Rumble Run Starter Decks

- Hearthstone Deck Tracker/Hearthstone/Player.cs
- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
- Hearthstone Deck Tracker/LogReader/LogConstants.cs
The card 'Spirit of the Dead' is getting some popularity recently, so this PR tries to fix the card tracking issue (fixes #3841).
Trackers are now able to track those card copies generated by the card 'Spirit of the Dead' for both the player and the opponent.
> Fix cards tracking for Spirit of the Dead

- HDTTests/HDTTests.csproj
- HDTTests/HsReplay/Utility/ShortIdHelperTests.cs
- Hearthstone Deck Tracker/HsReplay/Utility/ShortIdHelper.cs
This PR fixes short id generation to mirror https://github.com/HearthSim/hsredshift/pull/169. Previously we used an incorrect comparison method, whereas we want a mostly compatible Unicode Collation Algorithm. For us this means in practice we want a case-insensitive comparison step before the case-sensitive comparison.
Internally refs HSR-462.
> Fix HSReplay.net deck short id generation

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
This PR fixes #3988 and other similar problems(e.g., miscount of dream portals shuffled to opponent's deck by Ysera, Unleashed)
> Fix opponent cards tracking

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
This fixes #4010 
One of the two albatrosses created by Bad Luck Albatross is not tracked as  `GuessedCardState.Guessed`, which causes the leak.
> Fix Bad Luck Albatross

- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/IGameHandler.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
This PR implements cards tracking for `Madame Lazul` and other similar cards(e.g. `Mind Vision`).
The tag `COPIED_FROM_ENTITY_ID` is used when:
1. discover or copy cards from the opponent's hand, e.g. `Maname Lazul`, `Mind Vision`  <== _This is what we want to keep track of_
2. discover or copy cards from the opponent's deck, e.g. `Cloning Device`, `Thoughtsteal`
3. discover cards from own deck, e.g. `Tracking`, `Sightless Watcher`
Since it doesn't help much knowing which cards are in the opponent's deck, here we only keep track of known cards that are in the opponent's hand. And also, we don't want to handle cards copying initiated by the opponent to avoid info leak.
> Implement Madame Lazul card tracking

- Hearthstone Deck Tracker/Windows/OverlayWindow.Update.cs
It's not terribly useful information in battlegrounds, especially now with Bob's Buddy.
> Automatically hide player and opponent attack counter in battlegrounds

- Hearthstone Deck Tracker/Controls/Overlay/BobsBuddyPanel.xaml.cs
**NB:** I don't have a Windows dev machine and so with great regret I submit this patch untested.  I hope it's simple enough for someone to just read and try.
To explain the issue, suppose the probabilities are:
* 0.04% to lose
* 0.04% to tie
* 99.92% to win
* 99.88% to win with lethal
The chance to win is unequal to the chance to win with lethal, so that code is irrelevant.  Then these get rounded to:
* 0.1% to lose
* 0.1% to tie
* 99.9% to win
* 99.9% to win with lethal
The code that ensures W + L + T = 1 runs and we get:
* 0.1% to lose
* 0.1% to tie
* 99.8% to win
* 99.9% to win with lethal
No other adjustments are made and this gets displayed, which looks ridiculous even if on some level it reflects reality.
The proposed fix is just to clamp the lethal percentages to the win/loss …
> Fix issue 4079: ensure displayed lethal rates never exceed win/loss rates

- HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
This PR fixes several secret predictions when an attack happens:
- exclude `IceBarrier` if it is not triggered, no matter whether the attacker is removed from the play
- leave `Misdirection`/`SuddenBetrayal`/`Vaporize`/`FlameWard`/`FreezingTrap` in the pool of possibilities if they are not triggered when the attacker is removed from the play by secret like `Vaporize`/`FreezingTrap`
- exclude `SnakeTrap`/`VenomstrikeTrap` if they are not triggered, no matter whether the attacker is removed from the play by secret like `FreezingTrap`
Two test cases are added.
This will
- fix #3963 
- fix #3961
- fix #3850
> Fix secret handling when attack happens

- Hearthstone Deck Tracker/BobsBuddy/BobsBuddyInvoker.cs
- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Controls/Overlay/BobsBuddyPanel.xaml
- Hearthstone Deck Tracker/Controls/Overlay/BobsBuddyPanel.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayBattlegrounds.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayBattlegrounds.xaml.cs
- Hearthstone Deck Tracker/Hearthstone/BattlegroundsBoardState.cs
- Hearthstone Deck Tracker/Windows/DebugWindow.xaml
- Hearthstone Deck Tracker/Windows/DebugWindow.xaml.cs
Pass damage possibilites to the bb overlay
Add tooltip to average damage
Pass last combat damage dealt to bb panel
Add average damage tooltip messaging dependant on state
Change tooltip display based on state and possible results
Update tooltip offset when results are shown
Cast possibilities count
Link average damage opacity to damage possibilities
Note: this is temporary as we still haven't made the policy decision as to what the left/ right panels will show
Change soft label opacity to a classwide const
Default lethal and average damage to softly opaque
Smooth average damage panel transition
Add setting for showing average damage
Add extra casting to betterThanPortion
Change opponent av damage to red
Tooltip centering fix attempt
Add BB panel to debug window
Fix tooltip centering …
> Add average damgage to bob's buddy

- Hearthstone Deck Tracker/Utility/Assets/AssetDownloader.cs
https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/f7b70235276a3bec055795e06801242ece1d7b9b/Hearthstone%20Deck%20Tracker/Utility/Assets/AssetDownloader.cs#L230
```C#
public bool HasAsset(T obj)
{
if(obj == null)
return false;
var filename = _getFilename(obj);
return _succesfullyDownloadedImages.Contains(filename);
}
```
The filename you get from `var filename = _getFilename(obj);` contains file extension, why you get files without extension. It make the HDT always download the image file again and again.
> Fix download card image repeatedly when file exists

- Hearthstone Deck Tracker/Utility/WotogCounterHelper.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.Update.cs
The way C'Thun is dealt with in-game appears to have changed with the Caverns of Time Twist.
**Issues**
- Player entities never have their SEEN_CTHUN tag set
- C'Thun player/opponent proxies are no longer populated
- PlayerCthun and OpponentCthun entities are populated on the first play of a C'Thun subsidiary card but their attack/health values seem to lag actual values
**Changes**
- Hearthstone Deck Tracker/Utility/WotogCounterHelper.cs
- Use PlayerCthun/OpponentCthun existence to determine PlayerSeenCthun/OpponentSeenCthun values
- Hearthstone Deck Tracker/Windows/OverlayWindow.Update.cs
- Get Attack from CTHUN_ATTACK_BUFF player tag value
- Get Health from CTHUN_HEALTH_BUFF player tag value
Fixes #4490
> Fix Twist C'Thun

- Hearthstone Deck Tracker/Utility/BoardDamage/BoardCard.cs
- Add titan check and titan abilities used count
- Return false from IsAbletoAttack method if card is titan and still has unused abilities
- Issue #4503
> BoardCard class Titan compatibility

- Hearthstone Deck Tracker/Windows/OverlayWindow.MouseOverDetection.cs
Bos buddy was wrongly being displayed on hero picking after the first match. Checking the turn number ensures we only show Bobs Bubby after the first turn
> fix: bobs buddy showing on hero picking

- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
> feat: show minions top bar before and during hero picking

- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayBattlegrounds.xaml
> fix: always show Tavern Tier 7 setting disabled when Tier7 disabled

- Hearthstone Deck Tracker/Hearthstone/RelatedCardsSystem/Cards/Priest/ScaleReplica.cs
Fix an InvalidOperationException on `dragons.Min` when the current deck contains no dragons.
NB: The CLA signing info in the contributing file seems outdated.
> Fix InvalidOperationException on empty array

- Hearthstone Deck Tracker/Hearthstone/CounterSystem/Counters/PaladinCardsPlayedCounter.cs
Add a counter for played paladin cards. Useful for [Lightray](https://hearthstone.blizzard.com/en-us/cards/76258).
> feat: add paladin cards played counter
