HearthSim/Hearthstone-Deck-Tracker

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options.xaml.cs
- Hearthstone Deck Tracker/Hearthstone/Game.cs
- Hearthstone Deck Tracker/HsLogReader.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
- Hearthstone Deck Tracker/Replay/ReplayMaker.cs
Can be disabled in options -> Replay section.
> Original content of the HS log is saved to the replay file.

- Hearthstone Deck Tracker/DeckImporter.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Import.cs
Thank you so much for this great Tracker
http://www.hearthstoneheroes.de/
Example URL's
http://www.hearthstoneheroes.de/decks/legende-gvg-midrange-hunter-by-xixo/
http://www.hearthstoneheroes.de/decks/hells-hexenmeister/
...
> HearthstoneHeroes Support

- Hearthstone Deck Tracker/DeckImporter.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Import.cs
Add support for importing decks from elitedecks.net
> Support elitedecks.net

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/DeckExporter.cs
- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
- Hearthstone Deck Tracker/Hearthstone/Game.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Export.cs
! you need to delete config.xml to get the new default value. (or make it manual ExportCard1X,ExportCard2X, ExportCardY)
If you export a Deck you can now see what cards are in your collection missing and how much dust it cost to produce them.
http://i.imgur.com/bFbIFCP.png?1
I try to detect cards with the mana-crystal. Works better for me because of the higher difference to the background and it is on every card the same.
If a Card is exported twice i look at the botton if i can detect the lock (only one Card available).
This can be tricky if the card is glowing "New". i try to move the mouse over the card to remove that glow but i am not sure if this always help.
So please test it.
> Deck dust calculator

- Hearthstone Deck Tracker/DeckImporter.cs
Changed XPaths for new http://www.hearthstonetopdecks.com deck markup.
> Fix HSTopDecks import (#797)

- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
changes from the context menu affect the main window menu and the other way around
> Changed context menu. now has checkmarks when the options are activated.

- Hearthstone Deck Tracker/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/Plugins/PluginManager.cs
Made a small change that unloads plugins when the main window is closed, allowing to save some data or close windows etc.
> Unload plugins when the main window is closed

- HDTTests/HDTTests.csproj
- HDTTests/Hearthstone/DeckTest.cs
- Hearthstone Deck Tracker/DeckExporter.cs
- Hearthstone Deck Tracker/MainWindow/MainWindow_Load.cs
Changed "Heartstone" to "Hearthstone" a couple of times.
> Fixed spelling errors

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml.cs
- Hearthstone Deck Tracker/Hearthstone/Deck.cs
Solved half of my #1053 issue.
> Added option to use normal case for deck names instead of upper case.

- Hearthstone Deck Tracker/DeckImporter.cs
> Fix deck import for Hearthpwn's new layout

- Hearthstone Deck Tracker/HsLogReader.cs
- Hearthstone Deck Tracker/Replay/Enums/KeyPointType.cs
- Hearthstone Deck Tracker/Replay/TurnViewItem.cs
fixed iron juggernaut invalid deck issue (fixes #1171)
> fixed iron juggernaut invalid deck issue

- Hearthstone Deck Tracker/MainWindow/MainWindow_Edit.cs
Moved the assignment after the check for `null`.
> Bufgix for #1316 addressing null reference

- HDTTests/HDTTests.csproj
- HDTTests/Hearthstone/WebImportTest.cs
- Hearthstone Deck Tracker/DeckImporter.cs
Thought I'd fix some of the broken sites.
> Added tests and fixed some web importers

- HDTTests/Hearthstone/WebImportTest.cs
- Hearthstone Deck Tracker/DeckImporter.cs
Adds support for importing Hearthpwn Deck Builder decks
> Add support for Hearthpwn Deck Builder, fixes #1449

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/DeckStatsControl.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
- Hearthstone Deck Tracker/HearthStats/Controls/DownloadDecksControl.xaml.cs
- Hearthstone Deck Tracker/HearthStats/Controls/LoginControl.xaml.cs
- Hearthstone Deck Tracker/Hearthstone/GameV2.cs
- Hearthstone Deck Tracker/Utility/DataIssueResolver.cs
- Hearthstone Deck Tracker/Utility/Helper.cs
- Hearthstone Deck Tracker/Utility/Updater.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Edit.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Export.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Import.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_NewDeck.cs
- Hearthstone Deck Tracker/Windows/MessageDialogs.cs
> Add an option to disable dialog animation

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Load.cs
- Hearthstone Deck Tracker/Windows/MessageDialogs.cs
Flyouts animation is less annoying but since we have the option, this is more consistent.
I was updating #1622 but found it had been closed...
> UseAnimations affects flyouts as well

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Core.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerSettings.xaml.cs
- Hearthstone Deck Tracker/Windows/SplashScreenWindow.xaml.cs
Some asked for it so I added it.
*For the record I actually like the splash screen* :wink:
> Add an option to hide the splash screen

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Core.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerGeneral.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerGeneral.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
Added the option in Tracker->General.
is False by default.
Issue #1288
> added the option to automatically use no deck in spectator mode (#1288)

- Hearthstone Deck Tracker/Importing/ImportingHelper.cs
- Hearthstone Deck Tracker/Importing/Websites/Tempostorm.cs
TempoStorm changed the way decks are retrieved, using a GET with a json param.
> Update TempoStorm web import

- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Import.cs
This allows multiple files to be imported.
Forced auto save to allow multiple files at once.
Now using tabs.
> Import Multiple Files

- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPicker.xaml
- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPicker.xaml.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow.xaml
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow.xaml.cs
- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Edit.cs
Sometimes you want to update your deck from a different URL than the original import
> add option to assign or change constructed deck URLs

- Hearthstone Deck Tracker/Windows/MainWindow/MainWindow_Export.cs
Saves decks by name when multiple decks are selected.
Might want an option to turn this function on or off.
> Export Save As XML now supports multiple selected Decks

- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayGeneral.xaml
Just saw this while browsing through the menu and thought I might as well fix it.
> Fix a small spelling mistake.

- Hearthstone Deck Tracker/Utility/Helper.cs
> Remove card type from card sorting criteria

- Hearthstone Deck Tracker/Utility/Extensions/CardListExtensions.cs
Fixes #2669 for overlay and deck windows.
> Remove card type from card sorting criteria (part 2)

- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayPlayer.xaml
- Hearthstone Deck Tracker/Utility/WotogCounterHelper.cs
Renamed Yogg-Saron Counter to Spell Counter and made it work with the
arcane giant
> Spell Counter for Arcane Giant #2799

- Hearthstone Deck Tracker/Controls/Stats/ArenaFilters.xaml
- Hearthstone Deck Tracker/Controls/Stats/ConstructedFilters.xaml
> Add class filters translation

- Hearthstone Deck Tracker/GameEventHandler.cs
> Preselect first arena reward pack with current reward pack type

- Hearthstone Deck Tracker/Windows/OverlayWindow.Tooltips.cs
> Don't show flavor text on minion without it

- Hearthstone Deck Tracker/Windows/MainWindow.xaml
> Fix deck sort flyout text

- Hearthstone Deck Tracker/Stats/CompiledStats/ArenaStats.cs
> Fix filtered played class percentages in arena doughnut chart

- Hearthstone Deck Tracker/Utility/DataIssueResolver.cs
"do just do" and "talk too long" stuck out to me when first installing HDT today.
> Reword file-cleanup message

- Hearthstone Deck Tracker/Stats/CompiledStats/ArenaStats.cs
- Hearthstone Deck Tracker/Stats/CompiledStats/ConstructedStats.cs
> Fix "this week" filter for arena and constructed

- README.md
The badge colors were blue, while you can use color codes (like 738bd7 used here). This changes the discord badge colors to 738bd7.
> Update Discord badge colors

- Hearthstone Deck Tracker/Importing/Websites/Hearthstonetopdecks.cs
> Fix HearthstoneTopDecks import

- Hearthstone Deck Tracker/Windows/MainWindow.Edit.cs
This will check the URL for a new deck name when pressing Update (WEB).
#3108
> Update (web): check for new deck name

- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerPlugins.xaml.cs
While plugin browser is in review this can help with dragging and dropping.
> Drag and drop: Load plugins without requiring a restart

- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/Stats/CompiledStats/ArenaStats.cs
- Hearthstone Deck Tracker/Stats/CompiledStats/ConstructedStats.cs
- Hearthstone Deck Tracker/Stats/CompiledStats/DateTimeHelper.cs
Additionally, use the culture info for the first day of the week.
Fixes #3249
> Fix 'This week' stats filter

- Hearthstone Deck Tracker/Controls/Stats/Arena/ArenaStatsSummary.xaml
- Hearthstone Deck Tracker/Controls/Stats/Constructed/ConstructedSummary.xaml
> Fix localization of "show legends" checkbox in Stats

- Hearthstone Deck Tracker/Hearthstone/Player.cs
Hand and Deck are from PlayerEntities which is already filtered by
Player.IsControlledBy(Id).
> Simplify Player.HandCount/DeckCount

- Hearthstone Deck Tracker/Utility/BoardDamage/BoardCard.cs
- Hearthstone Deck Tracker/Utility/BoardDamage/BoardHero.cs
- Hearthstone Deck Tracker/Utility/BoardDamage/EntityHelper.cs
- Hearthstone Deck Tracker/Utility/HotKeys/PredefinedHotKeyActions.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.Tooltips.cs
Some quick spelling and formatting clean-up.
> minor speling and, grammar fixes

- Hearthstone Deck Tracker/Windows/MainWindow.xaml
- Hearthstone Deck Tracker/Windows/MainWindow.xaml.cs
> Don't show global statistics for arena games

- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsSearch.xaml.cs
- Hearthstone Deck Tracker/Utility/Helper.cs
Instead of hard-coding `CheckBox` as the type of option to search for, use a
base class `OptionWrapper`. Currently `CheckBoxWrapper` is the only concrete
child class, but more will be added for #3344.
Use a filter delegate to check whether an element is an "option" so we can
explicitly filter for `CheckBox` types, and for `DockPanel`s that contain a
`CheckBox`. In the future, `DockPanel`s that contain other types of controls
will also be selected. Finding the `DockPanel`s will let us find the related
text depending on the control type, as non-CheckBox types tend to have more
complicated UI.
This change should not affect search results today.
> Refactor OptionsSearch ahead of supporting more option types

- Hearthstone Deck Tracker/Controls/CardMarker.xaml
- Hearthstone Deck Tracker/Controls/CardMarker.xaml.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.Update.cs
> Implement scaling for CardMarks

- Hearthstone Deck Tracker/Utility/HotKeys/PredefinedHotKeyActions.cs
> Add Hotkey for My Games panel

- Hearthstone Deck Tracker/Hearthstone/Deck.cs
> Add poisonous and lifesteal mechanics

- Hearthstone Deck Tracker/Utility/Helper.cs
> Fix Launching Battle.net Beta

- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml
> Force black color for flavor text.

- HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs
- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsManager.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
> Add hidden cache secret tracking logic

- Hearthstone Deck Tracker/Utility/HotKeys/PredefinedHotKeyActions.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
> Fix hotkey for showing secrets panel

- Hearthstone Deck Tracker/Controls/Stats/Arena/ArenaStatsSummary.xaml
- Hearthstone Deck Tracker/Controls/Stats/Constructed/ConstructedSummary.xaml
Use the same margin as the group box for the expander
> Unify stats overview ui

- CONTRIBUTING.md
Made some changes to the CONTRIBUTING.md to clarify the setup steps for new developers, including a step to clone the repository in step 3.
> Clarify development setup steps in Contributing.md

- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPicker.xaml.cs
- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPickerItem.xaml.cs
- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPickerItemLayouts/DeckPickerItemLayout1.xaml
- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPickerItemLayouts/DeckPickerItemLayout2.xaml
- Hearthstone Deck Tracker/Controls/DeckPicker/DeckPickerItemLayouts/DeckPickerItemLayoutMinimal.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
- Hearthstone Deck Tracker/Windows/MainWindowControls/DeckChartsView.xaml.cs
> Fix refreshing of couple UI elements after change language

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
> Implement THE CANDLE tracking

- Hearthstone Deck Tracker/Windows/MainWindow.xaml
Remove margin to reduce empty space in stats flyout header
> Downsize stats flyout header

- Hearthstone Deck Tracker/Hearthstone/Deck.cs
> Fix stats updating under deck names

- Hearthstone Deck Tracker/Controls/CardToolTipControl.xaml
- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Utility/Helper.cs
> Unify font of card names

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
> Add weasel tunneler tracking

- Hearthstone Deck Tracker/Controls/AnimatedCardList.xaml.cs
> Ensure correct card order on overlay and deck windows

- Hearthstone Deck Tracker/Hearthstone/GameV2.cs
> Fix erroneously declaring the match info cache as valid

- Hearthstone Deck Tracker/Controls/ManaCurve.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs
When I changed the language setting, the combo box of the mana curve was not refreshed. So I corrected it.
> The combo box of the mana curve was not refreshed. 

- Hearthstone Deck Tracker/FlyoutControls/Options/OptionsMain.xaml
> Fix ScrollBar in options

- Hearthstone Deck Tracker/Stats/GameStats.cs
- Hearthstone Deck Tracker/Windows/MainWindow.Edit.cs
> Add localization

- Hearthstone Deck Tracker/FlyoutControls/DeckExport/DeckExportView.xaml
Fixes HearthSim/HDT-Localization#92
> Add localization for Deck code in DeckExportView

- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
> Avoid unnecessary rebuilds

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
fixed #3536 
make cards created by Shadow Reflection (not only Jade Idol) work correctly
> make cards created by Shadow Reflection work correctly

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Enums/HsActionType.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerGeneral.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerGeneral.xaml.cs
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerNotifications.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerNotifications.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/Hearthstone/Watchers.cs
- Hearthstone Deck Tracker/LogReader/Handlers/LoadingScreenHandler.cs
Resolves #3685, moved the Alerts section from General to Notifications. I've also added a new key (Options_Tracker_General_CheckBox_Popup_Challenge), but i don't how to add the translations using crowdin.
> HS Alerts (Flash & Popup)

- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerPlugins.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerPlugins.xaml.cs
The current options page for plugins looks a bit dull to me, so i redesigned it.
Merge if you like.
> [Options/Tracker/Plugins] Redesign

- Hearthstone Deck Tracker/Utility/HearthstoneRunner.cs
Resolves #3708 
Tested with standard and beta client.
> Hearthstone not launching

- Hearthstone Deck Tracker/FlyoutControls/Options/Tracker/TrackerGeneral.xaml.cs
> Fix initialization of auto archive arena run checkbox

- Hearthstone Deck Tracker/Hearthstone/HearthDbConverter.cs
> Treat Fireside Brawls as GameMode.Brawl

- Hearthstone Deck Tracker/Enums/ArenaRewardPacks.cs
> Fix Boomsday arena reward pack

- Hearthstone Deck Tracker/Hearthstone/GameV2.cs
Log every time names and ids are updated
> Improve match info logging

- Hearthstone Deck Tracker/Utility/XmlManager.cs
> Harden saving of config files

- Hearthstone Deck Tracker/Hearthstone/DungeonRun.cs
Updated the solo adventure mage decks, resolves #3808
> Updated solo adventure mage decks

- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
- Hearthstone Deck Tracker/LogReader/HsGameState.cs
> Add Grand Archivist opponent spell tracking

- Hearthstone Deck Tracker/Config.cs
- Hearthstone Deck Tracker/Controls/CardToolTipControl.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayGeneral.xaml
- Hearthstone Deck Tracker/FlyoutControls/Options/Overlay/OverlayGeneral.xaml.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.Tooltips.cs
Addresses feature request #3853.
> Adding row to card overlay displaying the card's set

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
This fixes #3848.
Note: Interaction with Augmented Elekk is still not handled.
> Fixed handling of Hakkar's Corrupted Blood in common cases.

- Hearthstone Deck Tracker/App.xaml.cs
- Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj
- Hearthstone Deck Tracker/Utility/Shell32.cs
> Set explicit AppUserModelID

- HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3996
- [ + ] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [ + ] I have already signed the CLA
> Misdirection is not excluded when the only potential target is immune

- Hearthstone Deck Tracker/BobsBuddy/BobsBuddyUtils.cs
> Have putrice and lich king delay their effects

- Hearthstone Deck Tracker/BobsBuddy/BobsBuddyInvoker.cs
- Hearthstone Deck Tracker/Utility/Analytics/Influx.cs
> Bb terminal case metric

- Hearthstone Deck Tracker/Controls/Overlay/BattlegroundsMinions.xaml.cs
> Remove zoobot from special minion available handling

- Hearthstone Deck Tracker/GameEventHandler.cs
This update gives more debug information about when the last attacking hero is set
> Add last attacking hero data

- Hearthstone Deck Tracker/Importing/StringImporter.cs
Fix #4272
Co-authored-by:  Urkaz <mrurkaz@gmail.com>
> Fix StringImporter ranked cards error

- Hearthstone Deck Tracker/Importing/StringImporter.cs
> Support multiclass cards with StringImporter

- Hearthstone Deck Tracker/Controls/Overlay/MulliganPanel.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
- [ x ] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [ x ] I have already signed the CLA
> Add filters for player initiative and rank on mulligan toast link

- Hearthstone Deck Tracker/Controls/Overlay/MulliganPanel.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Player.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.xaml.cs
> Fix mulligan toast player initiative after recent HS patch

- README.md
-  [x] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
The deck limit was raised to 27 with patch 20.0:
https://playhearthstone.com/en-us/news/23620129/introducing-the-core-set-and-classic-format.
> Update deck limit

- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Windows/OverlayWindow.DeckLists.cs
> Detect opponent decks with Maestra as rogues

- Hearthstone Deck Tracker/Hearthstone/GameV2.cs
- Hearthstone Deck Tracker/HsReplay/HSReplayNetOAuth.cs
- Hearthstone Deck Tracker/Utility/Twitch/TwitchApi.cs
> Use EBS to proxy game vod url request

- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
Fix for the issue https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/4379
> Filter spell counter from counting questlines parts

- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
- Hearthstone Deck Tracker/Hearthstone/Player.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
> Fix Immolation discarded cards leak

- Hearthstone Deck Tracker/Controls/Overlay/Battlegrounds/BattlegroundsGameViewModel.cs
- Hearthstone Deck Tracker/Controls/Overlay/Battlegrounds/BattlegroundsSessionViewModel.xaml.cs
- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/Utility/Battlegrounds/BattlegroundsLastGames.cs
> Session recap updates

- Hearthstone Deck Tracker/Hearthstone/Card.cs
- Hearthstone Deck Tracker/Hearthstone/Entities/Entity.cs
This PR adds spell schools to Card.cs for use in a multicaster plugin
> Mapped SpellSchool to HDT/Card.cs from hearthbCard

- Hearthstone Deck Tracker/GameEventHandler.cs
- Hearthstone Deck Tracker/IGameHandler.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
> Handle secrets countered by Blademaster Okami

- Hearthstone Deck Tracker/Hearthstone/CardIds.cs
- Hearthstone Deck Tracker/Hearthstone/IGame.cs
- Hearthstone Deck Tracker/Hearthstone/Secrets/SecretsEventHandler.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
> feat: implement Hidden Meaning secret

- Hearthstone Deck Tracker/LogReader/Handlers/PowerHandler.cs
- Hearthstone Deck Tracker/LogReader/Handlers/TagChangeActions.cs
- Hearthstone Deck Tracker/LogReader/HsGameState.cs
- Hearthstone Deck Tracker/LogReader/Interfaces/IHsGameState.cs
> fix: shuffle Plagues back to deck when affected by Plight Of The Dead
